language: php
php:
  - 5.5
  - 5.4

services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install
  
script:
  - phpunit --bootstrap ./tests/bootstrap.php tests